# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're
# live.

#define bookmarks_title Bookmarks
#define bookmarks_heading Bookmarks

#define bookmarks_toolbarfolder Bookmarks Toolbar Folder
#define bookmarks_toolbarfolder_description Add bookmarks to this folder to see them displayed on the Bookmarks Toolbar

# LOCALIZATION NOTE (getting_started):
# link title for https://www.mozilla.org/en-US/datalus/central/
#define getting_started Getting Started

# LOCALIZATION NOTE (datalus_heading):
# Datalus links folder name
#define datalus_heading Mozilla Datalus

# LOCALIZATION NOTE (datalus_get_help):
# link title for https://www.mozilla.org/en-US/datalus/help/
#define datalus_get_help Get Help

# LOCALIZATION NOTE (datalus_customize):
# link title for https://www.mozilla.org/en-US/datalus/customize/
#define datalus_customize Customize Datalus

# LOCALIZATION NOTE (datalus_community):
# link title for https://www.mozilla.org/en-US/contribute/
#define datalus_community Get Involved

# LOCALIZATION NOTE (datalus_about):
# link title for https://www.mozilla.org/en-US/about/
#define datalus_about About Us

# LOCALIZATION NOTE (nightly_heading):
# Datalus Nightly links folder name
#define nightly_heading Datalus Nightly Resources

# LOCALIZATION NOTE (nightly_blog):
# Nightly builds only, link title for https://blog.nightly.mozilla.org/
#define nightly_blog Datalus Nightly blog

# LOCALIZATION NOTE (bugzilla):
# Nightly builds only, link title for https://bugzilla.mozilla.org/
#define bugzilla Mozilla Bug Tracker

# LOCALIZATION NOTE (mdn):
# Nightly builds only, link title for https://developer.mozilla.org/
#define mdn Mozilla Developer Network

# LOCALIZATION NOTE (nightly_tester_tools):
# Nightly builds only, link title for https://addons.mozilla.org/en-US/datalus/addon/nightly-tester-tools/
#define nightly_tester_tools Nightly Tester Tools

# LOCALIZATION NOTE (crashes):
# Nightly builds only, link title for about:crashes
#define crashes All your crashes

# LOCALIZATION NOTE (planet):
# Nightly builds only, link title for https://planet.mozilla.org/
#define planet Planet Mozilla

#unfilter emptyLines
